"""manager chats

Revision ID: 417ed9ad6ca3
Revises: 705fbb7955a3
Create Date: 2025-07-04 16:06:24.931023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417ed9ad6ca3'
down_revision: Union[str, None] = '705fbb7955a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_chats'))
    )
    op.create_index(op.f('ix_manager_chats_chat_id'), 'manager_chats', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manager_chats_chat_id'), table_name='manager_chats')
    op.drop_table('manager_chats')
    # ### end Alembic commands ###
