"""banquet requests

Revision ID: 842d85ff3eeb
Revises: 417ed9ad6ca3
Create Date: 2025-07-04 23:53:08.646643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842d85ff3eeb'
down_revision: Union[str, None] = '417ed9ad6ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banquet_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banquet_date', sa.Date(), nullable=False),
    sa.Column('banquet_time', sa.Time(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_banquet_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banquet_requests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banquet_requests')
    # ### end Alembic commands ###
