"""add table_requests

Revision ID: c5944f0a9904
Revises: 3b394844b630
Create Date: 2025-07-05 01:49:38.714676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5944f0a9904'
down_revision: Union[str, None] = '3b394844b630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reserve_date', sa.Date(), nullable=False),
    sa.Column('reserve_time', sa.Time(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_table_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_requests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_requests')
    # ### end Alembic commands ###
